### ISSUE TITLE
error in idaapi.as_int32

### ISSUE THREAD

**Issue by 0x68ae** [idapython/src#53]
There seems to be an error here.
````
Python>idaapi.as_int32(0) == 0
False
Python>idaapi.as_int32(0) == idaapi.as_signed(0, 32)
False
Python>idaapi.as_signed(0, 32) == 0
True
Python>idaapi.as_int32(0)
-0x100000000
````

**Comment by KurobaM** [comment]
```
def as_int32(v):
    """Returns a number as a signed int32 number"""
    return -((~v & 0xffffffff)+1)
```

Python int do not have limit so (~v & 0xffffffff)+1) will never wrap. Can be fixed with

`return -((~v & 0xffffffff)+1) if v & 0x80000000 else v & 0xffffffff`

idaapi.as_signed also have bug. Value is not truncated down to nbits so you can get result much larger than (1<<nbits)-1
```
Python>idaapi.as_signed(0x17f, nbits=8)
0x17f

```

Can be fixed with: `return -(( ~v & ((1 << nbits)-1) ) + 1) if v & (1 << nbits-1) else v & ((1 << nbits)-1) `

**Comment by aundro** [comment]
Thank you very much for the report, and the proposed fix!

Please see https://github.com/idapython/src/commit/d81e2982b2d69bce3ddc7e57579555ab66fd083e
