### ISSUE TITLE
Python demangling does not ignore postfix _nn

### ISSUE THREAD

**Issue by e-ave** [idapython/src#56]
`demangle_name` always return None and `get_ea_name`, `get_long_name`, and `get_name` always return the unmangled name because of the postfix (.12345 or _1234) but names demangle fine in hex rays pseudocode since there is the "ignore postfix _nn" option in the settings.

`
print(idc.demangle_name("_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE.331187.100128", idc.get_inf_attr(idc.INF_SHORT_DN)))
`
None
`
print(idc.demangle_name("_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE.331187.100128", idc.get_inf_attr(idc.INF_LONG_DN)))
`
None
`
print(idc.demangle_name("_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE.331187.100128", idc.INF_LONG_DN))
`
None
`
print(idc.demangle_name("_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE.331187.100128", idc.INF_SHORT_DN))
`
None
`
print(idc.demangle_name("_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE.331187.100128", idaapi.cvar.inf.long_demnames))
`
None
`
print(idaapi.demangle_name("_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE.331187.100128", idaapi.cvar.inf.long_demnames))
`
None
`
print(idaapi.demangle_name("_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE.331187.100128", idaapi.cvar.inf.short_demnames))
`
None
`
idaapi.get_ea_name(ea, ida_name.GN_SHORT|ida_name.GN_DEMANGLED)
`
_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE.331187.100128
`
idaapi.get_ea_name(ea, ida_name.GN_LONG|ida_name.GN_DEMANGLED)
`
_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE.331187.100128

`
idc.get_name(ea, ida_name.GN_VISIBLE|idaapi.GN_DEMANGLED)
`
_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE_331187_100128

`
idc.get_long_name(ea, ida_name.GN_VISIBLE|idaapi.GN_DEMANGLED)
`
_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE_331187_100128

Hex Rays Pseudocode:
jag::graphics::FOGDISTANCE_DEFAULT

It requires manually removing the suffix with a custom function if you want it to actually demangle:

```
import re

def remove_mangled_postfix(symbol_name):
    # Remove suffixes with periods
    if "." in symbol_name:
        return symbol_name.split('.')[0]
    
    # Remove suffixes with underscores
    return re.sub(r'_[\d+_]+$', '', symbol_name)
```

`
print(idaapi.demangle_name(remove_mangled_postfix("_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE.331187.100128"), idaapi.cvar.inf.long_demnames))
`
jag::graphics::FOGDISTANCE_DEFAULT

`
print(idaapi.demangle_name(remove_mangled_postfix("_ZN3jag8graphicsL19FOGDISTANCE_DEFAULTE_331187_100128"), idaapi.cvar.inf.long_demnames))
`
jag::graphics::FOGDISTANCE_DEFAULT

But I feel that this shouldnt be necessary. All of the mangled symbols are going to have these suffixes since different signatures can generate the same mangled name. And this is only going to work on G++/GCC/itanium symbols. What if it were a different type of mangling? The remove_mangled_postfix would need special cases for all other mangling standards. 

Surely other IDA plugins are not jumping through this extra hoop? Am I doing something wrong?

**Comment by arizvisa** [comment]
Correct place would be to complain to support@ (especially since this repository is for IDAPython), but to sorta give back to the community and answer your question anyways...

IDA's demangler does not recognize the "." character which is likely why they're \_all\_ returning `None`. It works when you strip them, because you've stripped them. The underscore suffix, however, is special in that there's a flag ensure it gets stripped during the demangling process. However, it has a caveat which you're encountering in one of your examples.

The flag for the `ida_name.demangle_name` function that I'm referring to is `MNG_IGN_ANYWAY`. This can be used to remove any sequentially numbered (underscore-prefixed) suffix. The caveat, however, is that it only supports suffixes from 0 - 99 (afaik). As you pointed out that different mangled sequences can resolve to the same name and that demangling is also compiler-specific, that implicit suffix is specifically used to ensure that the actual name used by the name/netnode index is unique. As such, it gets stripped by the demangler when seen.

Actually, using the netnode api (and even `lvar_t`), you can store or rename items with practically any character (other than "\0"). This is because netnodes are really just an index for mapping an address/identifier to a name (and a few other types). Hence, you can change what characters you're allowed to use via the "NameChars" options and use them in any of your unmangled names (ftr: I include "`.:<>?!/,()`" in my "NameChars") as long as they're unique. This does not hold true, though, for things outside of this name/netnode index.

To elaborate, the netnode index is shared between all your global names, enumerations, and structures...all things that will likely require instant lookup by the disassembler. Thus, this index \_requires\_ each name to be unique, to the point where the disassembler will insert its own hidden prefix in order to meet this constraint and add it back when you are searching for things of certain types. That's where that sequential suffix comes from in your function names. Also in your examples, you're using "." as an alternative to "_". This character is also specially handled as the "." character is internally used as a separator between structure names and their members within the netnode/name index. Essentially, when you store funky characters to the netnode index for your naming information, if it's only \_fetched\_ by the disassembler/decompiler, it will render okay. However, if it is parsed (demangling or used in a type definition) it will not be usable.

To workaround this, you'll need to ensure that your funky names are actually parseable by the demangler whenever the disassembler/decompiler wants to parse it. This really only happens with type definitions (like function prototypes or variable types), so if you temporarily set it to something parseable and then restore it back afterwards, you'll likely be able to get by.

You can also go the route of writing your own name mangler and just ensuring you store your naming information into the netnode/name index in its mangled form...but then you could be having to maintain it for all the different compiler variations. You'll also have to support some of the backtick-quoted names that can be demangled like "<code>\`adjustor{...}'</code>", "<code>\`VTT for'</code>, or "<code>\`template static data member destructor helper'</code> unless you're okay with the discrepancy. It's also worth keeping in mind that there's a length constraint in that names that are too long will not be demangled.
